# Generated by Django 4.2.1 on 2023-05-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_description_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
