# Generated by Django 4.2.1 on 2023-05-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
    ]
